//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int idOrder { get; set; }
        public Nullable<int> idProduct { get; set; }
        public string quantity { get; set; }
        public string address { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
    }
}
